/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'OWNER' at '7/11/16 12:00 PM' with Gradle 2.14
 *
 * @author OWNER, @date 7/11/16 12:00 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
